nginx:
    restart: always
    build: ./nginx
    links:
        - node:node
    ports:
        - "80:80"
node:
    restart: always
    build: .
    ports:
        - "8000:8000"
    environment:
      - HOST=127.0.0.1
      - PORT=8000